version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    ports:
      - 443:443

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    expose:
      - 3306 

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    expose:
      - 9000

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 6379:6379

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    restart: always
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    ports:
      - 20:20 
      - 21:21 
      - 21100-21110:21100-21110

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pbeheyt/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pbeheyt/data/wordpress

networks:
  inception:
    driver: bridge