version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    ports:
      - 443:443

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    expose:
      - 3306 

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    expose:
      - 9000     

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pbeheyt/data/mysql
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pbeheyt/data/wordpress

networks:
  inception:
    driver: bridge